### ISSUE TITLE
OSX Mavericks Support

### ISSUE THREAD

**Issue by saada** [tugrul/node-mcrypt#7]
Any idea how to install the dependencies on an OSX machine?

**Comment by tugrul** [comment]
@HilkoLantinga the build fails because compiler says ~I didn't find the mcrypt.h header in your include path~ 

Can you check is there a mcrypt.h file in this path? https://github.com/tugrul/node-mcrypt/blob/master/binding.gyp#L10

I don't know the header file where in the OSX. Also you can find the library path and change `binding.gyp` and rebuild it.

Yeah the library not compatible with node v0.12 but latest stable is v0.11 currently. But im going to modify module to support v0.12

Thanks

**Comment by HilkoLantinga** [comment]
Please use https://github.com/rvagg/nan to secure future compatibility as well.

**Comment by tugrul** [comment]
@HilkoLantinga thank you so i published a new version. It looks like OK on OSX yosemite and node v0.11

**Comment by HilkoLantinga** [comment]
You are awesome! I'll do some quick tests with macports, brew, 10.x, 11.x and io.js as soon as I'm out of the restaurant.

**Comment by HilkoLantinga** [comment]
With Brew it does not work, still complains about the .h file, when I modify the bindings to "/usr/local/Cellar/mcrypt/2.6.8/include/" it gives: ld: library not found for -lmcrypt

**Comment by MauriceButler** [comment]
Any progress on using nan as this would solve many issues not just this OSX one?

If not I will have a crack at it but my C foo is very old...

**Comment by tugrul** [comment]
#16

**Comment by MauriceButler** [comment]
Very good. All working on io.js and node 0.0.12
